#端口
server:
  port: 8045
zuul:
  routes:
    user-consumer: /cjw/**
  strip-prefix: false
management:
  security:
    enabled: false


#要把这个服务注册到那个服务的地址
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:7099/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#Eurakeh中的名字
spring:
  application:
    name: zuul
