
server:
  port: 9002

#起名字
spring:
  application:
    name: turbine9002

#要把这个服务注册到那个服务的地址
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:7001/eureka
turbine:
  app-config: USER-CONSUMER-RUEBIN
  cluster-name-expression: "'default'"
  combine-host-port: true
